import React from 'react';
import ImageViewer from "components/ImageViewer/imageViewer";

import jenkins from './images/jenkins.png'
import jenkins_1843 from './images/Jenkins-at-1843-convention.png'
import d_jenkins  from './images/d_jenkins.jpg'
import neil_house  from './images/neil_house.png'
import fig_4  from './images/fig_4.png'
import fig_5  from './images/fig_5.png'
import fig_6  from './images/fig_6.png'


export default function(){

    return(
        <div style={{paddingLeft:10, paddingRight:10}}>
            <br />
            <br />
        <span ><span ><b>Editor, David Jenkins (1811 &ndash; September 5, 1877)</b></span></span>
            <br />
            <br /><span ><span >David Jenkins was born in Lynchburg, Campbell County, Virginia, in 1811.<a name="_ednref1" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a> His father, William Jenkins provided David with private tutors, noticing the young Jenkins&rsquo; potentials, till his knowledge was profound enough to teach younger siblings. It is not clear whether his father was white. However, no other records of black Jenkins have been discovered in Virginia. At least, Jenkins listed Virginia as his origin in the U.S. Census for 1850. He married Lucy Ann Mina James, a free person of color, on February 3, 1835, in his hometown.</span></span>
            <br />
            <br /><ImageViewer image={jenkins} width={300}/>  
            <br />
            <br /><span ><span >Jenkins moved to Columbus in 1837 with his wife and gained his fame as a community leader gradually. Although the founder and editor of the <i>Palladium of Liberty</i>, David Jenkins, has been forgotten like most of the Black leaders in 19<sup>th</sup>-century Ohio now, he was well-known to his contemporary people. Beginning with <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/278">the National Convention of Colored Citizens in Buffalo in 1843</a>, Jenkins as a delegate and committee members attended numerous state, national, and international conventions including to <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/324">the North American Convention held in Toronto, Canada in 1851</a> till 1871 when his name appeared the last in the Proceedings of <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/541">the Ohio State Convention of Colored Men</a>. He was elected as a president at the state convention, in 1851 and in 1856, and became one of the central committee members in 1852.</span></span>
            <br />
            <br /><ImageViewer image={jenkins_1843} width={600}/> 
            <br /><span ><span >[Figure 1] Jenkins is listed as a delegate in the Minutes of the National Convention of Colored Citizens; Held at Buffalo; on the 15<sup>th</sup>, 16<sup>th</sup>, 17<sup>th</sup>, 18<sup>th</sup>, and 19<sup>th</sup> of August, 1843. Courtesy of the Colored Conventions Projects] <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/278">https://omeka.coloredconventions.org/items/show/278</a></span></span>
            <br />
            <br /><span ><span >David Jenkins collaborated for Black civil rights movements with other prominent African Americans in Columbus including James Poindexter, John Ward, George Williams to organize the State Conventions of the Colored Citizens of Ohio, participated with the most Worshipful Grand Lodge, Free and Accepted Masons for the State of Ohio, and recruited for the 127<sup>th</sup> USCT Infantry Regiment during the Civil War. He also served as an agent of the Underground Railroad. John Ward recalls Jenkins:</span></span>
            <blockquote>
            <p><span ><span >Coming from a slave state he had neither education nor money. He found the condition of the colored people here littler better than it was in Virginia, and though circumstances were against him, he commenced in earnest his labors, looking to the elevation of his people.<span className="MsoEndnoteReference" style={{color:" rgb(5, 99, 193)", textDecoration: "underline", verticalAlign: "super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><a name="_ednref2" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn2">[ii]</a></span></span></span></span></span></span>
            </p>
            </blockquote>
            <br /><ImageViewer image={d_jenkins} width={200}/>
            <br /><span ><span >[Figure 2] Ward&rsquo;s interview on David Jenkins (<i>Ohio State Journal</i>, Feb. 25, 1870. Courtesy of Ohio History Connection; <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://ohiomemory.org/digital/collection/p16007coll22/id/49160/rec/9494">https://ohiomemory.org/digital/collection/p16007coll22/id/49160/rec/9494</a>)</span></span>
            <br />
            <br /><span ><span >The earliest record of David Jenkins can be found in Martin Robinson Delany&rsquo;s <i>The Condition, Elevation, Emigration, and Destiny of the Colored People of the United States</i>, first published in 1852. Delany&rsquo;s reference to Jenkins indicates that he was recognized by contemporaries outside of Ohio as well. In Chapter &ldquo;Professional Colored Men,&rdquo; he describes:</span></span>
            <blockquote>
            <p><span ><span >David Jenkins of Columbus, Ohio, a good mechanic, painter, glazier, and paper-hanger by trade, also received by contract, the painting, glazing, and papering of some of the public buildings of the State, in autumn 1847. He is much respected in the capital city of his state, being extensively patronized, having on contract, the great &ldquo;Neill House&rdquo; [<i>sic</i>], and many of the largest gentlemen&rsquo;s residences in the city and neighborhood, to keep in finish. Mr. Jenkins is a very useful man and member of society.<a name="_ednref3" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></a></span></span>
            </p>
            </blockquote>
            <br /><span ><span >As the <i>Palladium of Liberty </i>often quoted Delany&rsquo;s <i>The Mystery</i>, Pittsburgh-based Black newspaper at the same period as the <i>Palladium</i> and the agents invited him to local meetings, Delany was well acquainted with Jenkins&rsquo; versatile works for Black communities. Jenkins was listed as &ldquo;painter&rdquo; in the Columbus&rsquo;s city directories 1848, 1862-1872 and in the 1850, 1860 and 1870 Census. But his work exceeded &ldquo;painting,&rdquo; but was extended to large-scaled construction. For example, the exclusive Neil House hotel, whose construction Jenkins and his workers built, in Columbus demonstrated architectural achievements in the 19<sup>th</sup> century, and served Ohioans&rsquo; public gatherings for a long time.</span></span>
            <br />
            <br /><ImageViewer image={neil_house} width={400}/> 
            <br /><span ><span >[Figure 3. The three Neil House hotels on South High Street across from the Statehouse up until final hotel&rsquo;s demolition in 1981. &ldquo;Photos: The Historic Neil House Hotel.&rdquo; <i>The Columbus Dispatch</i>, August 13, 2012. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://www.dispatch.com/photogallery/oh/20120813/photogallery/308139859/PH/1">https://www.dispatch.com/photogallery/oh/20120813/photogallery/308139859/PH/1</a>]</span></span>
            <br />
            <br /><span ><span >David Jenkins hired Black apprentices and employees because he believed apprenticeship as a form of education that the white dominant society hindered through the notorious Black law and other racist practices. Like the advertisement suggests [Figure 4], David Jenkins and his wife, Lucy Ann Jenkins,<a name="_ednref4" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></a> looked for young Black men who wanted to learn painting business. His teaching of young employees was aligned with one article in the <i>Palladium of Liberty</i> that introduces a Black community in Mercer County, Ohio, as a model of Black advancement:</span></span>
            <blockquote>
            <p><span ><span >Young sable sons and daughters of America, whose minds are yet uncultivated, do you not feel the heavy burdens that has so long kept us in a state of degradation and blindness. I ask those of you who are employed in the most degrading occupations of life, will you not give up those offices and seek for more elevated ones. . . .. Education is the thing, and the only thing that can bring us in the scale of eminence. . . . There is not as many mechanics among our people, as there ought to be.<span className="MsoEndnoteReference" style={{color:" rgb(5, 99, 193)", textDecoration: "underline", verticalAlign: "super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><a name="_ednref5" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn5">[v]</a></span></span></span></span></span></span>
            </p>
            </blockquote>
            <br />
            <br /><ImageViewer image={fig_4} width={400}/> 
            <br /><span ><span >[Figure 4. &ldquo;Apprentices Wanted,&rdquo; <i>Palladium of Liberty</i>. This advertisement appears in most of the 32 issues of the newspapers.]</span></span>
            <br />
            <br /><span ><span >Jenkins&rsquo; dedication to Black education, especially focusing on practical skills in Ohio, started when he organized a &ldquo;school society&rdquo; with B. Roberts and C. Lewis and became trustees of the first school for African American children, presumably in 1837.<a name="_ednref6" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></a> Ferguson&rsquo;s study reveals that the society had insufficient budget for a school house, as the school was dependent on subscriptions while the Ohio Legislature did not offer any funding for Black schools. By August in 1840, 63 children were enrolled to the school that was maintained only for six months.</span></span>
            <br />
            <br /><span ><span >David Jenkins also ran a boarding house according to his advertisement [Figure 5]. In considering his work for the Underground Railroad, we can guess that this boarding house could have served as a site for plotting the Railroad among agents. In the antebellum period, his residence and shop, which functioned as a boarding house, was located on Friends and High Streets in Columbus.</span></span>
            <br />
            <br /><ImageViewer image={fig_5} width={400}/> 
            <br /><span ><span >[Figure 5. &ldquo;Boarding,&rdquo; <i>Palladium of Liberty</i>. This advertisement appears in most of the 32 issues of the newspapers.]</span></span>
            <br /><span ><span >After the Civil War, Jenkins was disappointed that systemic oppression of African Americans had persisted. He lamented: &ldquo;Except in Toledo, there are no (black) policemen, nor have there been any. No colored man has attained to the dignity of a deputy sheriff, deputy auditor, deputy recorder or deputy clerk.&rdquo;<a name="_ednref7" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn7"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vii]</span></span></span></span></a> It is unclear why he moved to Canton, Mississippi, after 1872 or 1873 when his name disappeared from the City Directory. Collins assumes that he might have accepted a position in Mississippi with the Freeman&rsquo;s Bureau or intended to improve the Southern city according to his Northern ideas, but no evidence proves either. After David Jenkins died on September 5, 1877, his widow, Lucy Ann, moved back to Columbus in 1899 and lived there till her death in 1899.</span></span>
            <br />
            <br /><span ><span ><b>Agents on the Move
            <br /></b></span></span>           
            <br /><span ><span >Agents of the <i>Palladium of Liberty</i> recruited subscribers, collected fees, delivered printed copies, and sent news on designated regions, while most of them maintained their own businesses and jobs.<i> </i>Some of them also served as writers by sending letter to the executive committee for publication.</span></span>
            <br />
            <br /><ImageViewer image={fig_6} width={400}/> 
            <br /><span ><span >[Figure 6. &ldquo;Agent Wanted.&rdquo; <i>Palladium of Liberty, </i>February 28, 1844, page 4</span></span>
            <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25889/rec/4">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25889/rec/4</a>]</span></span>
            <br />
            <br /><span ><span >As the newspaper was created as the resolution from the National Convention of Colored Citizens and the Ohio State Convention in 1843, the <i>Palladium of Liberty </i>was introduced as an exemplary of a Black newspaper in the following conventions and dispersed among convention delegates who served as agents for the newspaper. Nevertheless, it is not clear how the <i>Palladium of Liberty </i>reached out beyond Ohio; it had agents in Iowa and even Edinburgh in Britain in addition to the geographically close regions such as Lexington in Kentucky and Pittsburgh in Pennsylvania. Black residents in Pittsburgh could have better known about the <i>Palladium of Liberty </i>than any other big cities out of Ohio because of the editor&rsquo;s acquaintance with Martin R. Delany, who published <i>The Mystery</i>, the first Black newspaper in Pittsburgh.</span></span>
            <br />
            <br /><span ><span >Interestingly, the <i>Palladium of Liberty</i> was read and mentioned in New Hampshire where the newspaper did not have any agent and geographically located far away from Columbus, Ohio. On May 29, 1844, David Jenkins quotes the <i>Exeter Newsletter, </i>which was published on April 20: &ldquo;A number of Negroes in Columbus, Ohio, have commenced the publication of a Weekly Newspaper&rdquo; Here is his response: &ldquo;We wonder if the editor has just found out that the &lsquo;negroes,&rsquo; as he calls us, are to always keep silence; we find too much to do in the elevation of our colored race. The editor seems to cast reflections on us in noticing our paper. Why not notice our paper in a respectful manner? But no, he must use the word negroes instead of men of color. We don&rsquo;t intend to let anything mean in its bearing, like this pass our notice at home or abroad. We wonder if the News will exchange with us. We shall try the faith of that paper.&rdquo;<a name="_ednref8" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn8"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[viii]</span></span></span></span></a> Who brought the copy of the <i>Exeter Newsletter</i> is also unknown. This long list of the agents suggest that the <i>Palladium of Liberty</i> was on the move alongside with these agents during its publication period.</span></span>
            <br />
            <div>&nbsp;
            <hr width="100%" size="1" align="left" />
            <div id="edn1"><span ><span ><a name="_edn1" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a> Dennis Charles Hollins&rsquo;s PhD thesis, &ldquo;A Black Voice of Antebellum Ohio: A Rhetorical Analysis of <i>The Palladium of Liberty</i>, 1843-1844&rdquo; (Ohio State University, 1978) and Netti Ferguson&rsquo;s essay in <i>African-American Settlements and Communities in Columbus, Ohio: A Report</i> (Columbus Landmarks Foundation, 2014) offer well-researched biography of David Jenkins, although many parts of his life still remains untraceable. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://www.columbuslandmarks.org/wp-content/uploads/2019/02/African-American-Comm.pdf">https://www.columbuslandmarks.org/wp-content/uploads/2019/02/African-American-Comm.pdf</a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn2"><span ><span ><a name="_edn2" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></a> <span ><span >Ward, &ldquo;David Jenkins and His Work,&rdquo; <i>Ohio State Journal</i>, Feb. 25, 1870.</span></span></span></span>
                <br />&nbsp;
            </div>
            <div id="edn3"><span ><span ><a name="_edn3" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></span></span></a><span ><span > Martin Robinson Delany, <i>The Condition, Elevation, Emigration, and Destiny of the Colored People of the United States</i> (Black Classic Press, 1993), 99.</span></span></span></span>
                <br />&nbsp;
            </div>
            <div id="edn4"><span ><span ><a name="_edn4" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></span></span></a><span ><span > &ldquo;L. Jenkins&rdquo; may represent &ldquo;Lewis Jenkins&rdquo; who was listed on the Executive Committee of the newspaper and active in the state conventions in Ohio.</span></span></span></span>
                <br />&nbsp;
            </div>
            <div id="edn5"><span ><span ><a name="_edn5" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></a> <span ><span >D.D.D, Untitled, <i>Palladium of Liberty, </i>May 15, 1844, page 2.</span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25927/rec/13"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25927/rec/13</span></a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn6"><span ><span ><a name="_edn6" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></a> <span ><span >Netti Ferguson says that 1836 was the year he organized the society. But, as both Ferguson and Collins point out that Jenkins moved to Ohio in 1837, he must have organized it after his arrival to Ohio. <i>African-American Settlements and Communities</i>, 61.</span></span></span></span>
                <br />&nbsp;
            </div>
            <div id="edn7"><span ><span ><a name="_edn7" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref7"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vii]</span></span></span></span></a> <i><span ><span >Cincinnati Commercial</span></span></i><span ><span >, August 23, 1873. </span></span></span></span>
                <br />&nbsp;
            </div>
            <div id="edn8"><span ><span ><a name="_edn8" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref8"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[viii]</span></span></span></span></span></span></a><span ><span > Untitled, <i>Palladium of Liberty, </i>May 29, 1844, page 3.</span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25934/rec/8"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25934/rec/8</span></a></span></span>
                <br />&nbsp;
            </div>
            </div>
        </div>
    )
}