import React from 'react';
import ImageViewer from "components/ImageViewer/imageViewer";

import fig_14  from './images/fig_14.png'
import fig_15  from './images/fig_15.png'
import fig_16  from './images/fig_16.png'
import fig_17  from './images/fig_17.png'
import fig_18  from './images/fig_18.png'
import fig_19  from './images/fig_19.png'
import fig_20  from './images/fig_20.png'

export default function(){

    return(
        <div style={{paddingLeft:10, paddingRight:10, paddingTop:50}}>
            <span ><span >The <i>Palladium of Liberty</i> covered a broad range of topics, while focusing on particular issues in which black Ohioans were interested during the antebellum period: international and domestic politics, literature, news about black Ohioans, and local meeting announcements, especially state conventions of African American citizens.</span></span>
            <br />
            <br /><span ><span >Although the newspaper was published locally, it informed black communities in Ohio of in-state and out-of-state news as well as international subjects related to slavery and colonialism. This interactive map below indicates that the <i>Palladium of Liberty</i> used at least 62 periodicals for its sources. These periodicals include other contemporary black newspapers like Peter Clark&rsquo;s <i>Disfranchised American</i> and Martin Delany&rsquo;s <i>The Mystery</i>, in addition to nationally well-known newspapers like <i>New York Sun </i>and <i>Morning Courier and New York Enquirer</i>. The <i>Palladium of Liberty</i> also quoted from both abolitionist papers like <i>The Liberator</i> and Southern periodicals, <i>Richmond Enquire</i> and <i>Arkansas Traveler</i>.
            <br />
            <br />It is not clear how the editors collected these newspapers other than local and/or black newspapers. We can assume that the agents would not only recruit subscribers but also delivered to the editors various periodicals that they could obtain from subscribers and local acquaintances. Notably, the <i>Palladium of Liberty</i> also cited southern prints that blatantly revealed its pro-slavery agenda, in order to criticize their hypocrisy and immorality. The fact that the editor of the <i>Palladium of Liberty </i>obtained these southern periodicals hints at the newspaper team&rsquo;s effort to maintain its credibility by offering various sources for its articles.</span></span>
            <br />
            <br /><span ><span >The <i>Palladium of Liberty</i> focused on contemporary politics beyond abolitionism and slavery. One of the most frequently mentioned topics is the annexation of Texas. In 1843, President John Tyler without being aligned with any political party, decided to pursue the annexation of Texas. Through secret negotiations with the Houston administration, Tyler secured a treaty of annexation in April 1844, which became public immediately. Accordingly, pro-Texas-annexation southern Democratic delegates in alliance with pro-expansion northern Democrats nominated James K. Polk for the 1844 presidential election. In the issue on April 17, 1844 David Jenkins cited former President Andrew Jackson&rsquo;s letter for the support of the annexation, so that the newspaper could unhesitatingly criticize his proslavery and Manifest Destiny platform. &nbsp;&nbsp;</span></span>
            <blockquote>
            <p><span ><span >The design of this [Jackson&rsquo;s] letter is as foul as the bottomless pit, although it was written by one that has feasted at the public shrine, and enjoyed much of the loaves and fishes of our government be thinks now that he has a right to instruct the officers of the government.&nbsp; . . . He wants to make it appear that if they miss Texas, it will be a loss to the United States; he speaks like as if they had it, but would loose it if they were not careful. . . .We hope that every paper, in the country will rebuke the barefaced attempt to dupe the people, and bring them into difficulty, on the account of Texas.<a name="_ednref1" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a></span></span>
            </p>
            </blockquote>
            <br /><span ><span >The newspaper also reveals that the black communities in Ohio actively participated in politics by submitting petitions for establishing black schools and obtaining voting rights. According to the letter from W. Gassaway and G. Reynolds, who continuously attended the state conventions of colored citizens in mid-19<sup>th</sup> century Ohio, black and white residents in Zanesville gathered at the African Methodist Episcopal Church in the presence of David Jenkins. Jenkins raised a question about the Constitution and Statue from 1802 to the present legislature. At the meeting, they discussed &ldquo;the different bearings of those oppressive enactments against us as colored citizens [such as] removing from us our elective power, making no arrangements for the education f our children, denying us the proper source of justice in Courts, and collecting a tax off of us without giving us the benefit as other citizens.&rdquo;<a name="_ednref2" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></a> In particular, although education of black children and voting right were priority for early black communities in Ohio to ascertain their civil rights, the state law prevented them from exercising the rights while imposing taxes on African Americans. E. Moore of Bellevue wrote to the editor on August 28: &ldquo;We are compelled to pay school tax, but we are driven from the public schools, we are made to work pole tax, but we are driven from the poles, if we go to vote in time of war, we are driven to the field to protect the country. Shall I be silent under this state of things[?]&rdquo;<a name="_ednref3" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></a></span></span>
            <br />
            <br /><span ><span >To fight this systemic injustice against black Ohioans, the <i>Palladium of Liberty</i> functioned as a site to congregate political actions for black communities. For example, the newspaper circulated a petition form [Figure 14], so that many black residents could easily send this petition to the state legislature only by adding their names.</span></span>
            <br />
            <br /><ImageViewer image={fig_14} width={300}/> 
            <br /><span ><span >[Figure 14. <i>Palladium of Liberty</i>, October 23, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25995/rec/31">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25995/rec/31</a>]</span></span>
            <br />
            <br /><span ><span >The newspaper also facilitated and reported on meetings and lectures by prominent black leaders. For example, Martin Delany met with the editors and subscribers of the <i>Palladium of Liberty </i>over the one-year-long course of its run. The self-liberated people like Henry Bibb was also invited to testimony his experience under slavery and liberation, as the newspaper reported on August 14, 1844: &ldquo;On last Monday evening at the Baptist church, Mr. Bibb, a fugitive from slavery, lectured on the subject of slavery. The house was crowded to overflowing. After singing an appropriate song, he (Mr. Bibb) took the stand.&rdquo;<a name="_ednref4" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></a></span></span>
            <br />
            <br /><span ><span >The <i>Palladium of Liberty </i>was not an exception from the debate on African colonization and emigration of African descendants, which polarized black communities in the free states. Many letters to the editors published in the <i>Palladium of Liberty</i> suggest that black Ohioans in general objected the idea of African colonization and emigration. One article says: &ldquo;But must we go to African and leave all those that we have mentioned; as they may become content with these conclusions, no never, no never, who under heavens has placed us in our condition, who has torn us from our original homes, and now with a live branch of slavery, as this is the best name we can give it, reaching across the Atlantic ocean, biding us welcome to a land that flows with milk and honey[?]&rdquo;<a name="_ednref5" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></a></span></span>
            <br />
            <br /><span ><span >Alongside with politics, the newspaper weighed literary pieces significantly. The first pages of most issues include poems or short stories. While poems carry themes of Christian faith, morality, virtue, and freedom, short stories address the possible interest of young and women readers because they portray a young couple&rsquo;s love story and courtship, romance of a young black woman and marriage, and a young man&rsquo;s fantasy about a woman&rsquo;s virtue. These fictions were published under unidentifiable writers because of their pseudonyms like &ldquo;W.H. Carpenter&rdquo; and &ldquo;Wm. Comstock.&rdquo; One pseudonym is particularly noticeable: from the 21<sup>st</sup> issue, the newspaper published a series of &ldquo;Liberty Hymns,&rdquo; written by &ldquo;A. Freedomite.&rdquo;</span></span>
            <br />
            <br /><span ><span >Given that the themes and tones of these literary pieces seemed targeted at women audiences, especially black women, we may assume that the pseudonymous writers could be women writers who were associated with the editors of the <i>Palladium of Liberty</i>. [See one example of a black woman&rsquo;s love story. Figure 15.] For instance, the role of David Jenkins&rsquo; wife, Lucy Ann Jenkins does not appear apparently in the newspaper. Nevertheless, she could serve as a recruiter of local women writers, as black women often had meetings under the domestic-concerned name such as a &ldquo;sewing club&rdquo; at her residency. Otherwise, Lucy Ann Jenkins could offer her own writings, while aiding her husband&rsquo;s editorial work.</span></span>
            <br />
            <br /><ImageViewer image={fig_15} width={400}/> 
            <br /><span ><span >[Figure 15. &ldquo;A Fine Story,&rdquo; <i>Palladium of Liberty</i>, March 27, 1844, page 1. Note the protagonist describes as a beautiful young black woman without using clear racial identifications: &ldquo;She had glossy black hair, gentle, beaming eyes, and lips like wet coral.&rdquo; <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25898/rec/6">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25898/rec/6</a>]</span></span>
            <br />
            <br /><span ><span >For example, the editors posted a poem, &ldquo;Spring Verses,&rdquo; written by one 11 or 12 year-old girl who lived in Columbus. We can speculate that there was a story about a young girl whose writing had been circulated and complimented among the black community in Columbus. At one sewing meeting of black women, they agreed that the young poet&rsquo;s piece was worth sharing with the editors. Although women&rsquo;s presence in the public&mdash;even in print&mdash;could hardly be approved in the cult of the 19<sup>th</sup>-century &ldquo;True Womanhood,&rdquo; the <i>Palladium of Liberty</i> allowed the young woman writer to take the public platform to show her literary talent. Despite the absence of her name, the poet&rsquo;s voice was heard. Here is her poem [Figure 16].</span></span>
            <br />
            <br /><ImageViewer image={fig_16} width={250}/> 
            <br /><span ><span >[Figure 16. &ldquo;Spring Verses,&rdquo; <i>Palladium of Liberty</i>, June 12, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25942/rec/17">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25942/rec/17</a>]</span></span>
            <br /><span ><span ><i></i></span></span>
            <br /><span ><span >The literary pieces, published in the <i>Palladium of Liberty</i>, seemed to be widely appreciated beyond the black community in Columbus. And the quality of them was so excellent that other periodicals attempted to copy those of the black (mostly women) writers&rsquo; works. In the issue on June 26<sup>th</sup>, a warning message follows a poem, titled &ldquo;Speak Not A Better Word&rdquo; exclusively for the <i>Palladium of Liberty</i> under an acronym &ldquo;M.C&rdquo;: &ldquo;We hope when the &lsquo;Ohio State Tribune,&rsquo; in copying this poem, will do what is right.&mdash;One came from the same person, not long since, which the above paper took the liberty of copying without giving credit. We hope after this the Tribune will give the author what is due her.&rdquo;<a name="_ednref6" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></a> The <i>Palladium of Liberty</i> declared that the author should deserve &ldquo;her&rdquo; credit for &ldquo;her&rdquo; literary work that the white periodical, the <i>Ohio State Tribune</i>, had plagiarized it.</span></span>
            <br />
            <br /><span ><span >While the <i>Palladium of Liberty</i> published news in the local black community such as marriage announcement and moves, it also shows the specific hardships that black Ohioans in the antebellum period faced. Although Ohio was a free state, black communities in the state constantly experienced racial hatred, discriminatory practices, and harassments in addition to the state&rsquo;s legalization of the black law against new black residents from other states. For example, the newspaper reported on racial discrimination in public transportation where black people were ordered out of the State Coach (July 3, 1844). In another case, black people in Columbus were barred from white-owned stores (&ldquo;Don&rsquo;t Stop,&rdquo; August 28, 1844). Furthermore, black property owners often became the target of white mobs&rsquo; attack, according to the issue published on April 10, an article, &ldquo;More Barnburners!&rdquo; Even if lynching did not happen with the same frequency as that in the South, black people were often attached by whites, which were barely investigated by the authority. The newspaper on April 3, 1844, reported on a black man&rsquo;s death in an article, titled &ldquo;Outrage and Death&rdquo; [Figure 17]. According to the article, a black man was attached and beaten to death by three &ldquo;ruffians,&rdquo; but the justice system did not perform justice for black people: &ldquo;This man had one of his own color with him but what does this avail within we are deprived of justice in the courts of law and equity[?]&rdquo;</span></span>
            <br />
            <br /><ImageViewer image={fig_17} width={250}/> 
            <br /><span ><span >[Figure 17. &ldquo;Outrage and Death,&rdquo; <i>Palladium of Liberty</i>, April 3, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25900/rec/7">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25900/rec/7</a>]</span></span>
            <br />
            <br /><span ><span >As Ohio neighbors Kentucky and Virginia, both of which were slave states, the <i>Palladium of Liberty</i> suggests that black communities in Ohio still experienced the danger of slavery not only because they actively participated in the Underground Railroad to help self-liberated people from slave states, but also because active agents of slavery freely came to Ohio to &ldquo;hunt&rdquo; for former slaves and their allies. Along with articles on antislavery movements and illegal slave trades, the newspaper warned of slave hunters, who could be both black and white, as one article &ldquo;Look Out&rdquo; on May 15 suggests [Figure 18]. In another case, the black community in Columbus had a man, self-claimed fugitive slave, who turned out to be a slave hunter himself or at least attempted to dismantle black Ohioan&rsquo;s communal effort to build a strong community (&ldquo;Public Meeting,&rdquo; October 23, 1844).</span></span>
            <br />
            <br /><ImageViewer image={fig_18} width={300}/> 
            <br /><span ><span >[Figure 18. &ldquo;Look Out,&rdquo; <i>Palladium of Liberty</i>, May 15, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25927/rec/13">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25927/rec/13</a>]</span></span>
            <br />
            <br /><span ><span >Another shadow of slavery over Ohio can be seen in advertisements to look for lost family members. Most of family search advertisements appeared in black periodicals after the Civil War. Nevertheless, the <i>Palladium of Liberty </i>served former enslaved persons who liberated themselves and looked for family members, the people who were separated by slavery. Here are some examples published in the <i>Palladium of Liberty</i>:</span></span>
            <blockquote>
            <p><span ><span >&nbsp;&ldquo;Major Johnson, my brother, a lad of five years of age was taken, with other slaves, to the State of Tennessee, by John Johnston of Bartee county, North Carolina, in the year 1800, where he was left in the possession of Mr. Harry Pew, of said State. . . . The object of this advertisement is to obtain information of said Major, where he resides, if living. Should any person acquainted with him, chance to see this description, and would inform me by letter, or otherwise, would confer a lasting obligation on John Johnston of Columbus, Ohio.&rdquo;<a name="_ednref7" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn7"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vii]</span></span></span></span></a></span></span>
            </p>
            </blockquote>
            <blockquote>
            <p><span ><span >Information Wanted: Oberlin, Ohio, May 20, 1844&rdquo;: Nature prompts me to action. Some eighteen or twenty years ago, my father assumed the privilege of wringing from the hard hands of tyrants, and his unfortunate son has done the same thing; and it is my design to find him if it is possible. Thomas Fisher was his name, from Nashville Tennessee. He left a wife and two children. Mary Stump was his wife&rsquo;s name, and his son T. Fisher is now in Oberlin, Ohio. I supposed these lines will be sufficient. He lived four miles north of Nashville. The men&rsquo;s name that he lived with was Rice. I think that if this letter should reach him, or any person that is acquainted with him, I would be very much gratified if they would write to me.&rdquo;<a name="_ednref8" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn8"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[viii]</span></span></span></span></a></span></span>
            </p>
            </blockquote>
            <br /><span ><span >As a vehicle for black communities, the <i>Palladium of Liberty</i> promoted national and state conventions of black citizens. Just like the newspaper was a product of the 1843 national convention in Buffalo, New York, the editors organized groups of leaders, donors, participants, and volunteers for the 1844 state convention, which was held in Columbus, in September. For example, the newspaper ran an advertisement for Ladies&rsquo; Bazaar to fund the events at the convention, as Figure 8 illustrates (&ldquo;Who Read the <i>Palladium of Liberty </i>in the 1840s?&rdquo;). While we witness the state convention through the proceedings and minutes that report what happened inside of the convention, the <i>Palladium of Liberty</i> demonstrates how black people celebrated the communal action for black citizenship in addition to the convention meeting itself. David Jenkins and other committee members of the state convention planned for a rally outside of the convention site, and this announcement appeared more than five months till the convention took place on September 18<sup>th. </sup>[Figure 19]</span></span>
            <br />
            <br /><ImageViewer image={fig_19} width={250}/> 
            <br /><span ><span >[Figure 19. &ldquo;The Grand Rally,&rdquo; the <i>Palladium of Liberty</i>, April 10, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25904/rec/3">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25904/rec/3</a>] &nbsp;&nbsp;</span></span>
            <br />
            <br /><span ><span >Celebrations of black history and community building were not limited to conventions of African Americans. The <i>Palladium of Liberty </i>hints that black Americans commemorated the Emancipation of the West Indies in 1843 by celebrating the day, the first day of August. By contrast to their enthusiasm for the independence of the West Indies, it is notable that the newspaper remained quite about the Independence Day of the U.S., the Fourth of July. According to the newspaper, black citizens in Ohio held the celebration of the Emancipation of the West Indies at least in three cities: Harveysburg, Columbus, and Newark in 1844. After the celebration, the <i>Palladium of Liberty</i> reported on the one in Columbus: &ldquo;Elder Shelton, then proceeded to address the people on the great subject of emancipation which took place in the British West India Islands, on the first day of August in the year of our Lord 1838, at which time eight hundred thousand of our fellow beings were set at liberty.&rdquo; [Figure 20]</span></span>
            <br />
            <br /><ImageViewer image={fig_20} width={300}/> 
            <br /><span ><span >[Figure 20. &ldquo;Celebration of the 1<sup>st</sup> Day of August, in Columbus,&rdquo; the <i>Palladium of Liberty</i>, August 14, 1844, page 2. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25965/rec/23">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25965/rec/23</a>]</span></span>
            <br />
            <br />&nbsp;
            <div>&nbsp;
            <hr width="100%" size="1" align="left" />
            <div id="edn1"><span ><span ><a name="_edn1" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></span></span></a><span ><span > &ldquo;Another Letter from the Old Hero and Stateman,&rdquo; April 17, 1844, page 3.</span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25910/rec/43"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25910/rec/43</span></a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn2"><span ><span ><a name="_edn2" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></span></span></a><span ><span > &ldquo;Mr. Editor,&rdquo; <i>Palladium of Liberty</i>, March 20, 1844, page 2.</span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25892/rec/5">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25892/rec/5</a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn3"><span ><span ><a name="_edn3" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></span></span></a><span ><span > &ldquo;For the Palladium of Liberty,&rdquo; <i>Palladium of Liberty</i>, August 28, 1844, page 2.</span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25973/rec/25">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25973/rec/25</a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn4"><span ><span ><a name="_edn4" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></span></span></a><span ><span > &ldquo;Mr. Bibb,&rdquo; <i>Palladium of Liberty</i>, August 14, 1844, Page 2-3.</span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25965/rec/23">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25965/rec/23</a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn5"><span ><span ><a name="_edn5" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></span></span></a><span ><span > &ldquo;Colonization,&rdquo; <i>Palladium of Liberty</i>, August 28, 1844, page 3. </span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25973/rec/25">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25973/rec/25</a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn6"><span ><span ><a name="_edn6" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></span></span></a><span ><span > &ldquo;Speak Not A Better Word,&rdquo; <i>Palladium of Liberty</i>, June 26, 1844, page 3. </span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25949/rec/19">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25949/rec/19</a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn7"><span ><span ><a name="_edn7" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref7"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vii]</span></span></span></span></span></span></a><span ><span > &ldquo;Lost Brother,&rdquo; <i>Palladium of Liberty</i>, April 17, 1844, page 3. </span></span></span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25910/rec/43"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25910/rec/43</span></a></span></span>
                <br />&nbsp;
            </div>
            <div id="edn8"><span ><span ><a name="_edn8" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref8"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[viii]</span></span></span></span></a> &ldquo;Information Wanted: Oberlin, Ohio, May 20, 1844,&rdquo; <i>Palladium of Liberty,</i> June 5, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25938/rec/44">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25938/rec/44</a></span></span>
                <br />&nbsp;
            </div>
            </div>
        </div>
    )
}