import React from 'react';

export default function(){
    return(
        <div style={{paddingLeft:10, paddingRight:10, paddingTop:50}}>
            <span ><span >The <i>Palladium of Liberty </i>was established by the resolutions of two African American citizens&rsquo; conventions in the year of 1843.</span></span>
                <br />
                <br /><span ><span >In <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/278" >the National Convention of Colored Citizens, held at Buffalo, New York, in August 1843</a>, where David Jenkins attended as an Ohio delegate, the business committee announced its resolution: &ldquo;Resolved, That a weekly newspaper be established in some large city, which shall be the organ of the colored people and their friends, and that each member of this Convention pledge himself to procure subscribers for it, and that an executive committee be appointed by this Convention, under whose management the paper shall be published.&rdquo; Right after this resolution, the minutes says, &ldquo;On motion, so much of the report as referred to the establishment of a weekly newspaper was referred to the following committee for them to considering the subject and report thereon, viz,; Charles B. Ray, of New York, R. Banks, of Detroit; Wm. P. McIntire, of Albany; N.W.&rdquo; This indicates that the birth of the <i>Palladium of Liberty</i> was possible in the pre-existing networks of the Black press such as Ray&rsquo;s <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://chroniclingamerica.loc.gov/lccn/sn83027091/"><i>The Colored American</i></a> (1838) and Robert Banks&rsquo; <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://libraries.udmercy.edu/archives/special-collections/index.php?record_id=2017&amp;collectionCode=baa"><i>Weekly Advocate</i></a> (1837). Those journalists and editors, consisting of the committee on the Black press at the convention, delivered a significant speech:</span></span>
                <blockquote>
                <p><span ><span >The press takes hold of the public mind, and gets at the public heart; its influence reaches the spot to form and influence public opinion; and to what do the disabilities of the colored people and the slavery of this country owe their existence, more than to public opinion? . . . A paper such as it should be, necessarily conveys general information, and becomes a means of knowledge: no instrumentality is more efficient in conveying information upon general subjects than the newspaper press. If it be a means of knowledge, then it aids in the formation of character, and every family, especially where there are children, ought to take a newspaper for the information it contains. But if papers tend to the formation of character, then ought we to see to it that papers only of correct sentiments come into the hands of our children.<a name="_ednref1" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a></span></span>
                </p>
                </blockquote>
                <br /><span ><span >In the same year, David Jenkins also attended <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/1593">the State Convention of Colored People in Ohio, held in August 10th, 11th, and 12th, 1843, Columbus</a>. According to the <i>Philanthropist</i>, David Jenkins was appointed as Vice President as well as Samuel Jones of the Convention. Under Jenkins&rsquo;s editorship, the listed members of the convention served as the local agents for the <i>Palladium of Liberty</i>.<a name="_ednref2" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></a> This overlap between the conventions and the newspaper tells us that the newspaper served as a tool to advocate African American citizenship from their civil engagement to education of younger generations. The inaugural issue of the <i>Palladium of Liberty</i> included the convention speech on <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/files/original/3846b1483fa69cad8e3a595f7376ad2f.pdf">the first page</a>:</span></span>
                <blockquote>
                <p><span ><span >WE ARE AMERICANS; and as Americans, we desire all the rights and immunities of <i>American Citizens</i> . . . . Give us, fellow countrymen, citizenship in fact, and America will not rank among her friends and supporters, more firm, more patriotic, more devoted men to her true interests, in peace and in war, than her colored sons. . . . We do not ask you to abolish your form of government; but we ask that you would repeal all laws and parts of laws that make a distinction on account of color, and which degrade us on that account.<a name="_ednref3" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></a></span></span>
                </p>
                </blockquote>
                <br /><span ><span >This speech shows that the newspaper aimed at achieving Black Ohioans&rsquo; civil rights as equal to their fellow white citizens. The <i>Palladium of Liberty</i> has been introduced narrowly as an abolitionist paper, as the Ohio History Connection summarizes the newspaper.<a name="_ednref4" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></a> However, like many other Black periodicals, the <i>Palladium of Liberty </i>proposed to promote the country&rsquo;s recognition of African Americans as citizens who must deserve government-sanctioned freedom and rights, beyond the abolition of slavery. The following article explicitly asserts the newspaper&rsquo;s agenda by echoing the national convention&rsquo;s resolution: &ldquo;[W]e establish a weekly newspaper for an organ of the colored people, and the same to be printed in this city [Columbus].&rdquo;<a name="_ednref5" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></a> For example, one letter from M.M. Clark of Cincinnati reads, &ldquo;I would be an abolitionist but I think I can do more for the people of color as I am, than any other way.&rdquo;<a name="_ednref6" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_edn6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></a> At the beginning, the <i>Palladium of Liberty </i>had 15 executive committee members under David Jenkins&rsquo; leadership, which reduced to 7 from the third issue, 39 local agents, 18 agents outside of Ohio, and 14 traveling agents.</span></span>
                <br />&nbsp;
                <div>&nbsp;
                <hr width="100%" size="1" align="left" />
                <div id="edn1"><span ><span ><a name="_edn1" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a> &ldquo;The Minutes of the National Convention of Colored Citizens, held at Buffalo, New York, in August 1843; for the Purpose of Considering Their Moral and Political Condition as American Citizens,&rdquo; <i>Colored Conventions.</i> <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/278">https://omeka.coloredconventions.org/items/show/278</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn2"><span ><span ><a name="_edn2" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></a> &ldquo;1843 Ohio State Convention held Columbus, Ohio,&rdquo; <i>The Philanthropist</i>, November 4, 1843. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://omeka.coloredconventions.org/items/show/1592">https://omeka.coloredconventions.org/items/show/1592</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn3"><span ><span ><a name="_edn3" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></a> &ldquo;Address to the Citizens of Ohio,&rdquo; <i>Palladium of Liberty,</i> December 27, 1843, page 1. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25874">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25874</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn4"><span ><span ><a name="_edn4" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></a> &ldquo;The <i>Palladium of Liberty,</i>,&rdquo; The African-American Experience in Ohio 1850 &ndash; 1920, Ohio History Connection. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="http://dbs.ohiohistory.org/africanam/html/nwspaper/liberty.html">http://dbs.ohiohistory.org/africanam/html/nwspaper/liberty.html</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn5"><span ><span ><a name="_edn5" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></a> &ldquo;Address to the Citizens of Ohio,&rdquo; <i>Palladium of Liberty,</i> December 27, 1843, page 2. &nbsp;<a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25874">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25874</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn6"><span ><span ><a name="_edn6" title="" style={{color:"#0563c1", textDecoration:"underline"}} rel="noopener noreferrer" href="#_ednref6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span style={{fontSize:10.0}}><span >[vi]</span></span></span></span></a> <span ><span >&ldquo;Abolitionist But,&rdquo; <i>Palladium of Liberty</i>, February 21, 1844, page 3.</span></span></span></span>
                    <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25884/rec/10"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25884/rec/10</span></a></span></span>
                    <br />&nbsp;
                </div>
                </div>
        </div>
    )
}