import React from 'react';
import ImageViewer from "components/ImageViewer/imageViewer";

import fig_7  from './images/fig_7.png'
import fig_8  from './images/fig_8.png'

export default function(){
    return(
        <div style={{paddingLeft:10, paddingRight:10}}>
            <span ><span >According to the <i>Palladium of Liberty</i>, the number of African Americans in Ohio in 1839 was 17,362,<a name="_ednref1" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a> &nbsp;and 573 (9.5% of the total population) only in Columbus in 1840.<a name="_ednref2" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></a> The same article in the newspaper says that they should obtain about 2,500 subscribers to maintain its publication and distribution. The estimate numbers turned out not ambitious enough because the actual payment from the subscribers fell too short to continue to publish the <i>Palladium of Liberty.</i> Nevertheless, the <i>Palladium of Liberty</i> was read by a variety of groups, as the newspaper covered a wide range of topics centering issues on contemporary African American experiences and interests.</span></span>
                <br />
                <br /><span ><span >Since the newspaper had a strong network of agents, its subscribers were dispersed mostly across Ohio. [Click the graphs for a bigger image with subscribers&#39; names and amount of monetary contributions.]                
                <br />&nbsp;Although the <i>Palladium of Liberty </i>targeted on African Americans under its motto, &ldquo;Devoted to the interests of the colored people generally,&rdquo; the list of the subscribers included whites as well. For example, a letter from a person named S.H.B in Wooster says, &ldquo;Seeing that many of my colored friends are engaged in writing for your paper, and I being a regular subscriber, thought it not but right that I should send you, a line or two. . . I moreover want to see your very excellent paper sustained, and you cannot expect that it will be done unless some of your subscribers help to hear the burthen.&rdquo;<a name="_ednref3" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></a> The writer does not reveal his name, supposedly because his friendship with Blacks could offer any clue of him not only as an abolitionist but also as an Underground Railroad agent. Nevertheless, his attention to the Black newspaper indicates that the contemporary whites were aware of Black communities&rsquo; effort to achieve civil rights.</span></span>
                <br />
                <br /><span ><span >Another notable reader group of the <i>Palladium of Liberty </i>was women. It is impossible for us to estimate any contribution of David&rsquo;s wife, Lucy Ann, to the newspaper. One of the executive committee members, &ldquo;L. Jenkins,&rdquo; may stand for &ldquo;Lewis Jenkins&rdquo; rather than &ldquo;Lucy Ann Jenkins.&rdquo; However, a feminist tone is prevalent in the newspaper, questioning a preconception that the Victorian discourse on womanhood would be applied to Black women as well as whites. As one article, titled &ldquo;Female Influence&rdquo; insists, &ldquo;Female influence is now felt in all the relations of life since woman has been elevated to a proper station in society; her influence on individual happiness, and all prosperity is so good that every attempt to render it more beneficial is praise-worthy&rdquo; without limited to the domestic sphere.<a name="_ednref4" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></a> One conversation between a &ldquo;smart child&rdquo; and his mother exposes the irony of gender hierarchy in language [Figure 7].</span></span>
                <br />
                <br /><ImageViewer image={fig_7} width={400}/> 
                <br /><span ><span >[Figure 7. &ldquo;Smart Child.&rdquo; <i>Palladium of Liberty</i>, March 20, 1844, page 3</span></span>
                <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25892/rec/5"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25892/rec/5</span></a>]</span></span>
                <br />
                <br /><span ><span >More specifically, the newspaper addresses for working women when it quotes from Delany&rsquo;s article &ldquo;Young Women&rdquo; in <i>The Mystery</i>:</span></span>
                <br />
                <br /><span ><span >Several persons have spoken to us, and lastly, an esteemed friend who writes to us, says, &ldquo;that a good many of our people think that you should not fault our women for living out at service, that we are a poor people, and they must do something for an honest living.&rdquo; This induces us to make the explanation, especially for the satisfaction of our industrious young females. Certain, we say, it is no disgrace, to live out, or to do any honest work for a living when necessity so compels us. . . . Yours is necessity, the young white lady&rsquo;s is choice. She&rsquo;s to blame, you are not.<a name="_ednref5" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></a></span></span>
                <br />
                <br /><span ><span >In addition to working women, the <i>Palladium of Liberty</i> shares mothers&rsquo; concern about raising children by offering a piece of advice: &ldquo;Take especial pains to make home the most pleasant place on earth to them. . . . The memory of <i>home, sweet home, </i>happy early association and a mother&rsquo;s love, watchfulness and prayers, have been the talisman which has enabled many a soul to bear up and buffet in after years against the winds of adversity and the tide of temptation which have assisted them through a long life.&rdquo;<a name="_ednref6" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></a> Mothers or married women were considered decision makers of Black households. Along with various tips on house management, the newspaper encouraged wives to tell their husbands that they should pay for the subscription, as &ldquo;The being and well-being of the paper is in your hands!&rdquo;<a name="_ednref7" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn7"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vii]</span></span></span></span></a></span></span>
                <br />
                <br /><span ><span >The <i>Palladium of Liberty</i> notes women&rsquo;s societies as important contributors to Black communities through announcements and articles. For examples, the Female Union Sewing Society was frequently announced to have a weekly meeting: &ldquo;The Female Union Sewing Society will meet this evening, at Mr. D. Jenkins&rsquo; at early candle-lighting; we would like to see a good turnout, as union is strength,&rdquo; and sometimes with an additional comment: &ldquo;[C]ome let every female be present, at this meeting and make a strong pull, and all pull together&rdquo; in the May 1, 1844 issue. Black women politicized their sewing skills as a power to unite and to support Black Ohioans financially, which helped us imagine what kind of conversation they would have over their busy hands with threads and needles. They sold their works at the 1844 state convention site [Figure 8] and collected $67, approximately $2,335.68 in 2020, during the fair.</span></span>
                <br />
                <br /><ImageViewer image={fig_8} width={400}/> 
                <br /><span ><span >[Figure 8. &ldquo;Ladies Fair.&rdquo; <i>Palladium of Liberty,</i> June 26, 1844, page 3. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25949/rec/19"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25949/rec/19</span></a>]</span></span>
                <br />
                <br /><span ><span >Other Black leaders were also envisioned as readers of the <i>Palladium of Liberty</i>. The newspaper addressed politically organized actions for Black civil rights by introducing good models like Martin Delany: &ldquo;[T]he editor of the mystery [Martin Delany] in noticing our paper says he hopes that the editor may be courageous, unyielding and independent to his several duties. We will use all the energies we possess to carry out the great principles of our people.&rdquo;<a name="_ednref8" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn8"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[viii]</span></span></span></span></a> These leaders not only consisted of nationally famous figures but also included local business owners. For example, one article argues that barbers could professionalize themselves to help Black communities united:</span></span>
                <br />
                <br /><span ><span >My object is, to call their [barbers&rsquo;] attention to the necessity and propriety of forming themselves into a society, not only for mutual aid and benefit in time of sickness and distress, but for the purpose also, of sustaining the respectability of their profession. . . . Rules might be adopted, both in respect to apprentices and journeymen, and also for the general regulation of the profession, which would be an advantage to all concerned, and have a tendency to unite us in friendship, instead of leaving us a prey to envy and jealousy one against another.<a name="_ednref9" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_edn9"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ix]</span></span></span></span></a></span></span>                
                <br /><span ><span >This article emphasizes a barber&rsquo;s significant role to consolidate a Black community when his shop should serve as a site where Black people could communicate and organize to help one another.</span></span>
                <br />&nbsp;
                <div>&nbsp;
                <hr width="100%" size="1" align="left" />
                <div id="edn1"><span ><span ><a name="_edn1" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref1"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[i]</span></span></span></span></a> &ldquo;Address to the Citizens of Ohio,&rdquo; <i>Palladium of Liberty,</i> December 27, 1843, page 3. &nbsp;<a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25874">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25874</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn2"><span ><span ><a name="_edn2" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref2"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ii]</span></span></span></span></a> Campbell Gibson and Kay Jung, &ldquo;Historical Census Statistics on Population Totals by Race, 1790 to 1990, and by Hispanic Origin, 1970 to 1990, For Large Cities and Other Urban Places in the United States. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://www.census.gov/population/www/documentation/twps0076/twps0076.pdf">https://www.census.gov/population/www/documentation/twps0076/twps0076.pdf</a><u> </u>Accessed on March 3, 2020.</span></span>
                    <br />&nbsp;
                </div>
                <div id="edn3"><span ><span ><a name="_edn3" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref3"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iii]</span></span></span></span></a> &ldquo;Letter to Editor from S.H.B. in Wooster,&rdquo; <i>Palladium of Liberty</i>, June 12, 1844, page 2. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25942/rec/17">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25942/rec/17</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn4"><span ><span ><a name="_edn4" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref4"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[iv]</span></span></span></span></span></span></a><span ><span > &ldquo;Female Influence,&rdquo; <i>Palladium of Liberty,</i> April 10, 1844, page 2.</span></span></span></span>
                    <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25902/rec/7">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25902/rec/7</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn5"><span ><span ><a name="_edn5" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref5"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[v]</span></span></span></span></a> Martin Delany, &ldquo;Young Women,&rdquo; <i>Palladium of Liberty</i>, February 21, 1844, page 2. <a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25884/rec/10">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25884/rec/10</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn6"><span ><span ><a name="_edn6" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref6"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vi]</span></span></span></span></a> <span ><span >Untitled, <i>Palladium of Liberty</i>, February 28, 1844, page 3. </span></span></span></span>
                    <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25888/rec/19"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25888/rec/19</span></a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn7"><span ><span ><a name="_edn7" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref7"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[vii]</span></span></span></span></span></span></a><span ><span > &ldquo;To Subscribers,&rdquo; <i>Palladium of Liberty, </i>May 8, 1844, page 1</span></span></span></span>
                    <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25925/rec/12">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25925/rec/12</a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn8"><span ><span ><a name="_edn8" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref8"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[viii]</span></span></span></span></a> <span ><span >Untitled, <i>Palladium of Liberty</i>, March 27, 1844, page 3. </span></span></span></span>
                    <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25896/rec/20"><span style={{color:"blue"}}>https://digital-collections.columbuslibrary.org/digital/collection/african/id/25896/rec/20</span></a></span></span>
                    <br />&nbsp;
                </div>
                <div id="edn9"><span ><span ><a name="_edn9" title="" style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="#_ednref9"><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span ><span className="MsoEndnoteReference" style={{verticalAlign:"super"}}><span ><span >[ix]</span></span></span></span></span></span></a><span ><span > J.B., &ldquo;Letter to Editor,&rdquo; <i>Palladium of Liberty</i>, July 10, 1844, page 1.</span></span></span></span>
                    <br /><span ><span ><a style={{color:"#0563c1", textDecoration:"underline"}} target="_blank" rel="noopener noreferrer" href="https://digital-collections.columbuslibrary.org/digital/collection/african/id/25958/rec/21">https://digital-collections.columbuslibrary.org/digital/collection/african/id/25958/rec/21</a></span></span>
                    <br />&nbsp;
                </div>
                </div>
        </div>
    )
}